name: Build and Push to ACR

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: todo-add-tasks-api
      IMAGE_TAG: v4
      ACR_NAME: test32971
      ACR_LOGIN_SERVER: test32971.azurecr.io

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: Azure/login@v2.3.0
        with:
          client-id: 234de938-4362-4348-afa5-f2d70e633da7
          tenant-id: 0866c35f-f17c-4158-9075-0be761513841
          subscription-id: 2fe6adb6-b639-4804-8d25-87b437c9cbe6

      - name: Log in to ACR
        run: |
          az acr login --name $ACR_NAME

      # ðŸ”‘ REQUIRED for buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # âœ… Correct build for AKS (amd64)
      - name: Build and Push Docker Image
        run: |
          docker buildx build \
          --platform linux/amd64,linux/arm64 \
          -t test32971.azurecr.io/todo-add-tasks-api:v4 \
          --push .

